services:
  trippyweb:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
    profiles:
      - full_app
    networks:
      - backend
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.6.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: yes
      MYSQL_DATABASE: trippy
      MYSQL_USER: trippy
      MYSQL_PASSWORD: trippy
      MARIADB_DATABASE: trippy
      MARIADB_USER: trippy
      MARIADB_PASSWORD: trippy
    ports:
      - "33060:3306"
    networks:
      - backend
networks:
  backend: {}
volumes:
  db_data: {}
